### ISSUE TITLE
unable to find module 

### ISSUE THREAD

**Issue by piyushcoader** [GeekyAnts/react-native-easy-grid#1]
/node_modules/react-native-easy-grid/Components/Row.js: Unable to find this module in its module map or any of the node_modules directories under /Volumes/node_modules/multiplier and its parent directories

**Comment by sankhadeeproy007** [comment]
Fixed with `0.1.2`

**Comment by piyushcoader** [comment]
when will that be released?

**Comment by rpocklin** [comment]
Looks like it was on the same day.
