### ISSUE TITLE
Col.js: Unexpected token (32:8)

### ISSUE THREAD

**Issue by rlacon** [GeekyAnts/react-native-easy-grid#104]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/react-native-easy-grid/issues
- [x]   Use the latest React Native Easy Grid release
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

### node, npm, package.json, xcode version
Node: v12.16.3
NPM: 6.14.4
package.json: version: 0.1.0
xcode: Version 11.3.1 (11C504)

### Expected behaviour
react-native-easy-grid should compile correctly. 

### Actual behaviour
In the Col.js file, it seems to believe there is an unexpected token in the TouchableOpacity component. It states: node_modules/react-native-easy-grid/Components/Col.js: Unexpected token (32:8)

### Steps to reproduce

Run npm start from the root folder.

    'use strict';

    import React, { Component } from 'react';
    import { View, TouchableOpacity, StyleSheet } from 'react-native';
    import computeProps from '../Utils/computeProps';

    export default class ColumnNB extends Component {
      prepareRootProps() {

        var flattenedStyle = StyleSheet.flatten(this.props.style)

        var type = {
          flexDirection: 'column',
          flex: (this.props.size) ? this.props.size : (flattenedStyle && flattenedStyle.width) ? 0 : 1,
        }
    
        var defaultProps = {
          style: type
        }
        return computeProps(this.props, defaultProps);
    
      }
    
      setNativeProps(nativeProps) {
        this._root.setNativeProps(nativeProps);
      }
    
      render() {
        if (this.props.onPress) {
          return (
            <TouchableOpacity onPress={this.backArrow}
              {...this.prepareRootProps()}>
              <View
                ref={component => this._root = component}
                {...this.props}
                {...this.prepareRootProps()}
             >{this.props.children}</View>
            </TouchableOpacity>
          );
        }
        else {
          return (
            <View
              ref={component => this._root = component}
              {...this.props}
              {...this.prepareRootProps()}
            >{this.props.children}</View>
          );
        }
      }

### Any other additional info which would help us debug the issue quicker.
![UnexpectedError](https://user-images.githubusercontent.com/16549552/85205652-af381100-b2ea-11ea-9217-d763543111d5.png)

**Comment by akshoy1997** [comment]
How to solve this? Please help

**Comment by icgarlin** [comment]
Was this ever solved?
