### ISSUE TITLE
<Row size={-1}>

### ISSUE THREAD

**Issue by RailtonMatthew** [GeekyAnts/react-native-easy-grid#12]
This isn't an issue per se, just an observation I would like clarification on.

If I use `<Row size={-1}>` then the height of the row is set to the minimum required to show the content.  If size is set to 0 then there is additional padding.  Using -1 is very useful but is it safe to use?

The same behaviour occurs when using `<Col size={-1}>`

Thanks,

Railton.

**Comment by sospedra** [comment]
This has to be in the docs :)
