### ISSUE TITLE
Grid layout is not Displaying in 0.37 version

### ISSUE THREAD

**Issue by kajeevan025** [GeekyAnts/react-native-easy-grid#17]
Hi guys,

I am running latest react native version 0.37 with easy grid installed 
npm install react-native-easy-grid --save
But I am not able to see Grid layouts working as expected (as react-native 0.35)
 react native version is "react-native": "0.37.0"
easy grid version is  "react-native-easy-grid": "^0.1.6"

**This sample code where i was testing the grid**

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import { Col, Row, Grid } from "react-native-easy-grid";

export default class GridTest extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text>Start of Grid</Text>
        <Grid>
          <Row>
            <Col>
              <Text>First Row First Column</Text>
            </Col>
          </Row>
          <Row>
            <Col>
              <Text>Second Row Second Column</Text>
            </Col>
          </Row>
        </Grid>
        <Text>End of Grid</Text>
      </View>
    );
  }
}



AppRegistry.registerComponent('GridTest', () => GridTest);
```

Could you please help.

**Comment by SupriyaKalghatgi** [comment]
@kajeevan025 Could you share screenshot of your simulator for this?

**Comment by kajeevan025** [comment]
![grid](https://cloud.githubusercontent.com/assets/17445457/20751157/4b91b616-b720-11e6-8bf3-de58f9ba32ff.png)

**Comment by kajeevan025** [comment]
I think it have problem in COLUMN because i removed <COL> tag it is displaying the Text.
May be column have some small issue ..

**Comment by ravitez** [comment]
Same issue here the layout is off after my upgrade,so went back to Vanilla react native layout

**Comment by klinkov** [comment]
"react-native": "0.38.0"
"react-native-easy-grid": "0.1.6"

when add from example
`<Grid>
    <Col>1</Col>
    <Col>
        <Row>2</Row>
        <Row>3</Row>
    </Col>
</Grid>`
got
**Possible Unhandled Promise Rejection (id: 0):
Cannot read property 'getHostNode' of null
TypeError: Cannot read property 'getHostNode' of null**

**Comment by SupriyaKalghatgi** [comment]
@klinkov Minor error with the syntax
```
<Grid>
  <Col><Text>1</Text></Col>
  <Col>
    <Row><Text>2</Text></Row>
    <Row><Text>3</Text></Row>
  </Col>
</Grid>
```

But definitely not `getHostNode`
Not because of Easy-Grid

**Comment by klinkov** [comment]
@SupriyaKalghatgi 
I got from Example 6. Nested Layout or Grid

ok, i'll try again

**Comment by SaurabhKshirsagar** [comment]
I have same issue grid is not visible.
![capture](https://cloud.githubusercontent.com/assets/22885250/21217255/4b43cad4-c2d1-11e6-81fb-96215fce0e8b.PNG)

**Comment by nvme978** [comment]
I'm facing the same issue on 0.1.7
Anyone found the solution yet?

**Comment by anupkale1984** [comment]
I am facing same issue with 0.1.8 version on React native 0.38.
It works when it is under Native Base component like <Container> <ListItem> etc.
But fails if used outside thus, moved back to Plain react native <View>

Please, let us know if any solution available.

**Comment by millersdev** [comment]
Im facing this issue as well, what to do, any ideas allready?

**Comment by AngSin** [comment]
Same issue for me still

**Comment by AngSin** [comment]
It works in scrollview tags though, in case anyone needs to use it and they don't care about using it inside a scrollview
