### ISSUE TITLE
Flow Errors in Col/Grid/Row Components

### ISSUE THREAD

**Issue by frontendloader** [GeekyAnts/react-native-easy-grid#26]
flow-bin@0.37.4
react-native-easy-grid@0.1.8

Resolution: Add annotations, or remove `//@flow` from affected files

    node_modules/react-native-easy-grid/Components/Col.js:25
     25:     setNativeProps(nativeProps) {
                            ^^^^^^^^^^^ parameter `nativeProps`. Missing annotation

    node_modules/react-native-easy-grid/Components/Col.js:26
     26:       this._root.setNativeProps(nativeProps);
                    ^^^^^ property `_root`. Property not found in
     26:       this._root.setNativeProps(nativeProps);
               ^^^^ ColumnNB

    node_modules/react-native-easy-grid/Components/Col.js:34
     34:       ref={component => this._root = component}
                                      ^^^^^ property `_root`. Property not found in
     34:       ref={component => this._root = component}
                                 ^^^^ ColumnNB

    node_modules/react-native-easy-grid/Components/Col.js:44
     44:       ref={component => this._root = component}
                                      ^^^^^ property `_root`. Property not found in
     44:       ref={component => this._root = component}
                                 ^^^^ ColumnNB

    node_modules/react-native-easy-grid/Components/Grid.js:37
     37:     setNativeProps(nativeProps) {
                            ^^^^^^^^^^^ parameter `nativeProps`. Missing annotation

    node_modules/react-native-easy-grid/Components/Grid.js:38
     38:       this._root.setNativeProps(nativeProps);
                    ^^^^^ property `_root`. Property not found in
     38:       this._root.setNativeProps(nativeProps);
               ^^^^ GridNB

    node_modules/react-native-easy-grid/Components/Grid.js:46
     46:       ref={component => this._root = component}
                                      ^^^^^ property `_root`. Property not found in
     46:       ref={component => this._root = component}
                                 ^^^^ GridNB

    node_modules/react-native-easy-grid/Components/Grid.js:56
     56:       ref={component => this._root = component}
                                      ^^^^^ property `_root`. Property not found in
     56:       ref={component => this._root = component}
                                 ^^^^ GridNB

    node_modules/react-native-easy-grid/Components/Row.js:26
     26:     setNativeProps(nativeProps) {
                            ^^^^^^^^^^^ parameter `nativeProps`. Missing annotation

    node_modules/react-native-easy-grid/Components/Row.js:27
     27:       this._root.setNativeProps(nativeProps);
                    ^^^^^ property `_root`. Property not found in
     27:       this._root.setNativeProps(nativeProps);
               ^^^^ RowNB

    node_modules/react-native-easy-grid/Components/Row.js:35
     35:         ref={component => this._root = component}
                                        ^^^^^ property `_root`. Property not found in
     35:         ref={component => this._root = component}
                                   ^^^^ RowNB

    node_modules/react-native-easy-grid/Components/Row.js:45
     45:             ref={component => this._root = component}
                                            ^^^^^ property `_root`. Property not found in
     45:             ref={component => this._root = component}
                                       ^^^^ RowNB

**Comment by brenmcnamara** [comment]
I'm also getting these errors. Looks like this was published back in January, has anyone looked into this?

flow-bin: 0.45.0
react-native-easy-grid: 0.1.7

**Comment by brenmcnamara** [comment]
It looks like you're not really using flow type checking. There is no `.flowconfig` file in your repo and you don't have flow-bin listed in your `package.json` file as a dependency. If you're not using flow, please remove any `/* @flow */` annotations in your javascript files. If you use these annotations, then anyone importing this module who is actually using flow will end up with all your flow errors.
