### ISSUE TITLE
StyleSheet.create object is not working

### ISSUE THREAD

**Issue by frpram** [GeekyAnts/react-native-easy-grid#27]
```        <Col style={{width: 15}}>```-> works
```
const styles = StyleSheet.create({
  col: {
    width: 50,
 }
});
<Col style={styles.col}> ``` --> doesnt work

**Comment by agungjk** [comment]
@frpram i faced same problem with you, so try this :

`
const styles = {
  col: {
    width: 50,
 }
};
<Col style={styles.col}>
`

**Comment by TroyMaeder** [comment]
I'm facing the same problem. Did you find a solution for this @frpram ? I know there's a performance gain in using the ```StyleSheet.create``` so hoping there's a fix for this : )

**Comment by Shaz88Al** [comment]
StyleSheet.create will generate ids for the objects. to convert back to object by using 
For details you can refer http://facebook.github.io/react-native/releases/0.43/docs/stylesheet.html#flatten
One way is StyleSheet.flatten(styles.col). This will give you object

**Comment by 3210jr** [comment]
Hi all!
Im facing the same issue, has anyone come up with a fix for this?

**Comment by akhil-geekyants** [comment]
Working in the latest version (0.1.15)

Gif

![stylesheet](https://user-images.githubusercontent.com/27768184/34522063-edf7e706-f0b6-11e7-8937-32fb0c0d8df2.gif)

**Comment by charliecap** [comment]
> @frpram i faced same problem with you, so try this :
> 
> ```js
> const styles = {
>   col: {
>     width: 50,
>  }
> };
> <Col style={styles.col}>
> ```

This literally saved me a ton of time tonight. Thank you!

**Comment by vannhan2812** [comment]
Did you import StyleSheet ?

**Comment by GardenofJungwonLee** [comment]
I faced the same problem. After importing 'StyleSheet' , then it works!:)
