### ISSUE TITLE
0.1.9 is broken

### ISSUE THREAD

**Issue by ujwal-setlur** [GeekyAnts/react-native-easy-grid#34]
version 0.1.9 severely breaks under react-native 0.44.0. Haven't tried other react-native versions.

v0.1.8 works. This took me 4 hours in the wee hours of my birthday to hunt down :-(

My package.json had 
```
"react-native-easy-grid": "^0.1.8"
```
So when I reinstalled node_modules, it automatically got 0.1.9 since it was a minor version upgrade. A minor version bump should not cause this kind of breakage.

![img_0234-18-05-17-02-43](https://cloud.githubusercontent.com/assets/5835869/26224905/66c6f8d6-3bd9-11e7-8e3c-aa8e06ea6f4d.PNG)
Screenshot attached

**Comment by SupriyaKalghatgi** [comment]
Fixed with [0.1.10](https://github.com/GeekyAnts/react-native-easy-grid/releases/tag/0.1.10)
