### ISSUE TITLE
Failing react packager after travis addition

### ISSUE THREAD

**Issue by vongohren** [GeekyAnts/react-native-easy-grid#36]
This commit https://github.com/GeekyAnts/react-native-easy-grid/commit/82526c8d36b1caaca9ddf6e3e111140fa2bec799 gives an error in react packager when using this library @Jasbir23 

It complaines about duplicate module name with react and react-native.
This issue kinda explaines it: https://github.com/aksonov/react-native-router-flux/issues/1809

So i believe after you added react-native and react as dependencies for your travis tests, it breaks now for simple usage of the library.

This might be solved with removing dependencies that is just for tests, and added them to devDependencies rather than the dependencies object.

**Comment by Jasbir23** [comment]
Thanks for the input here @vongohren, Looking into this.

**Comment by Jasbir23** [comment]
Hey @vongohren I hope this fixes it 4e3f8915c16edca53f52941de1fe00f4cf88d6cc

**Comment by vongohren** [comment]
Looks promising, cant confirm until friday though :(

**Comment by vongohren** [comment]
I can confirm it works
