### ISSUE TITLE
Screen content moved by Keyboard

### ISSUE THREAD

**Issue by JMurilloM** [GeekyAnts/react-native-easy-grid#37]
Hello, I have a Issue with screen, only with Android version, when I click into inputs and Keyboard appears, all the screen make like 1 ROW and rearrange all of my content, Any ideas? I searched and I don't find anything

<img width="1589" alt="screen shot 2017-06-14 at 3 52 55 pm" src="https://user-images.githubusercontent.com/3254713/27158102-ee95803e-5119-11e7-8489-da6646e6bd93.png">

**Comment by MaxiSantos** [comment]
can you put some code? Is there any way we can help? Is still happening? I'd like to use this library but not if this is still an issue.

**Comment by akhil-geekyants** [comment]
@JMurilloM if you are using NativeBase components place `<Grid/>` inside NativeBase `<Content/>` component. Read more about NativeBase screen structure [here](http://docs.nativebase.io/Components.html#anatomy-headref) .

**Comment by dgdavid** [comment]
@JMurilloM, @akhil-geekyants 

At least on Android, I solved it changing the value of `android:windowSoftInputMode` from `adjustResize` to `adjustPan` in the _android/app/src/main/AndroidManifest.xml_ file.

**Comment by akhil-geekyants** [comment]
@JMurilloM @dgdavid above code with NativeBase `<Content/>` component. Read about Content component [here](http://docs.nativebase.io/Components.html#anatomy-headref)

Gif

![content](https://user-images.githubusercontent.com/27768184/35148452-328161c6-fd38-11e7-9686-6c44231af840.gif)

**Comment by dgdavid** [comment]
@akhil-geekyants I saw your previous request. But the thing is that I was not using `NativeBase`, only the `react-native-easy-grid` library. It would be great to could use it without additional dependencies.

That said, thanks so much for your support.

**Comment by akhil-geekyants** [comment]
@dgdavid above implementation with React Native components

Gif

![screencontent](https://user-images.githubusercontent.com/27768184/35218161-9321d2b0-ff93-11e7-9b1f-e429bce0ee0e.gif)

**Comment by dgdavid** [comment]
Oh, nice!

So, `Grid` must be wrapped into a `ScrollView`, isn't it?

I think that I also tested it before creating my own `Row` and `Column` layout components, but looking your attached gif I am not sure now if I did it right.

Againg, thanks a lot for your help.

**Comment by SupriyaKalghatgi** [comment]
@JMurilloM The solution provided solves your issue
