### ISSUE TITLE
Why did 0.1.11 come after 0.1.13?

### ISSUE THREAD

**Issue by ujwal-setlur** [GeekyAnts/react-native-easy-grid#41]
0.1.13 was done in May. 0.1.11 was done in July. Why? This is messing up the yarn package manager.

May 24: 52835afbe18f31cd52a41db9f8787ec9e7c35c4e --> 0.1.13
July 8: 730f3edf60e17b60ea653ef8cba1801be7fc3c42 --> 0.1.11

yarn fetches the latest which it thinks is 0.1.13, but that breaks with react-native 0.46. v0.1.11 came later and works with react-native 0.46

**Comment by sankhadeeproy007** [comment]
Fixed with 0.1.14
