### ISSUE TITLE
ReactNativePropRegistry not found for react-native >= 0.44

### ISSUE THREAD

**Issue by tspecht** [GeekyAnts/react-native-easy-grid#42]
Hey!

I'm currently trying to get this running with react-native >= 0.44. Unfortunately the imports seem to be wrong:

```
error: bundling: UnableToResolveError: Unable to resolve module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` from `my-project/node_modules/react-native-easy-grid/Utils/computeProps.js`: Module does not exist in the module map or in these directories:
  my-project/node_modules/react-native/Libraries/Renderer/shims
,   my-project/node_modules/react-native/Libraries/Renderer/shims

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ResolutionRequest._resolveNodeDependency (my-project/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:394:11)
    at ResolutionRequest.resolveDependency (my-project/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:141:29)
    at dependencyNames.map.name (my-project/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (my-project/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:42)
    at Promise.resolve.then (my-project/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:169:21)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

I suspect this is highly related to https://github.com/GeekyAnts/NativeBase/issues/307? If yes I guess those fixes should be applied here also? I'd be willing to contribute those but wanted to make sure first that is actually something both wanted & needed.

Thanks
Tim

**Comment by poptocrack** [comment]
There is a workaround : 
`npm install --save react-native-easy-grid@0.1.13`
Install this version until they fix the 0.1.11. It seems there is also a mistake ine the version number, 0.1.11 is the latest.

**Comment by yukkeechang** [comment]
@poptocrack Do you understand why that error keeps popping up? And how does installing easy-grid help?

**Comment by poptocrack** [comment]
No i don't know why does this error is still here, probably an update from the react native code not followed by the GeekyAnts team.
The error doesnt appear with the 0.1.13 version.
For some reasons, when you use `npm install react-native-easy-grid`  it downloads the 0.1.11.

**Comment by younatics** [comment]
I made pull request for this issue.
https://github.com/GeekyAnts/react-native-easy-grid/pull/43

**Comment by ashishprajapati** [comment]
I am facing the same
```
"react": "^16.0.0-alpha.6",
 "react-easy-grid": "^1.0.2",
 "react-native": "^0.43.3",
  
```

**Comment by tquiroga** [comment]
Really annoying one. I've tried pretty much all versions and keep getting that error... Can we have a list of what version is compatible with what?

**Comment by poptocrack** [comment]
Did you make `npm init` ? the plugin is working fine for me with the latest version

**Comment by bobmulder** [comment]
Same error for me though, version 0.49 of react native...

**Comment by SupriyaKalghatgi** [comment]
Thank you bringing this to notice
we will look into this
and also add a table for compatibility versions with React Native

**Comment by bobmulder** [comment]
That sounds good @SupriyaKalghatgi. When do you expect to have it fixed? (can't nearly work on my project now because of this bug :().

**Comment by akhil-geekyants** [comment]
Not present in the latest React Native versions.

Gif

![reactnativeprop](https://user-images.githubusercontent.com/27768184/34518216-7aa881dc-f0a4-11e7-8587-f70af8c4ebaa.gif)

Closing the issue
