### ISSUE TITLE
Anyway to make the grid square?  

### ISSUE THREAD

**Issue by wootwoot1234** [GeekyAnts/react-native-easy-grid#49]
I want to make a calendar.  So I want each row to have 7 columns and I want the columns to be the same height as they are wide.  My app will run on iPhones and iPads so it needs to scale.  Is that possible?

**Comment by akhil-geekyants** [comment]
@wootwoot1234 you can get the screen width using [Dimensions](https://facebook.github.io/react-native/docs/dimensions.html#docsNav) from react-native.

```
const width = Dimensions.get('window').width;
const sideLength = width / 7;
```
and set the column height and width

```
<Col style={{ height: sideLength, width: sideLength }}><Text style={{ color: 'black' }}>{item}</Text></Col>
```
