### ISSUE TITLE
StyleSheetRegistry renamed  to ReactNativePropRegistry (as of 0.24)

### ISSUE THREAD

**Issue by michshat** [GeekyAnts/react-native-easy-grid#5]
Thank you for this lib very lightweight and easy to use!

Any chance to update `StyleSheetRegistry` to `ReactNativePropRegistry` in the `Util` class?

**Comment by Nubuck** [comment]
I have an open PR for the RN 0.25 compat issues

**Comment by michshat** [comment]
@Nubuck that's really awesome. Thanks!

**Comment by Nubuck** [comment]
@michshat if you're in a hurry to ship like I was, you can install it like this in your package.json:
```json
  "react-native-easy-grid": "nubuck/react-native-easy-grid"
```

**Comment by michshat** [comment]
That's really great. I wasn't aware of that technique. Thank you!

**Comment by himanshu-sahusoft** [comment]
I have merged the PR now. Sorry for the delay.

**Comment by Nubuck** [comment]
@himanshu-sahusoft thanks so much. Such a great implementation of Flexbox!

**Comment by michshat** [comment]
Thank you.
