### ISSUE TITLE
Mapping Columns: Using fixed number of columns

### ISSUE THREAD

**Issue by fullhdpixel** [GeekyAnts/react-native-easy-grid#55]
Here's what I want: create 3 columns in a row and then a new row. I've tried to use size={3} as Column property. That doesn't work. What is a better solution?

```
<Content>
  <Grid>
    {topics.map((prop, key) => {
      return (
          <Col style={{ backgroundColor: prop.color, height: 200 }} size={3}>
            <Text style={{ color: "white" }}>
              {prop.name} {key}
            </Text>
          </Col>
      );
    })}
  </Grid>
</Content>
```

**Comment by akhil-geekyants** [comment]
@fullhdpixel 

use 3 `<Col/>` in a `<Row/>` and display the `<Row/>` as a set

```
<Row>
  <Col >
    <Text >One</Text>
  </Col>
  <Col >
    <Text >Two</Text>
  </Col>
  <Col >
    <Text >Three</Text>
  </Col>
</Row>
```

**Comment by fullhdpixel** [comment]
@akhil-geekyants thanks for the effort, but that's not what I mean. I want to map from an array of "topics" to a grid consisting of 3 columns per row.

Anyway, it was answered [here on stackoverflow](https://stackoverflow.com/questions/48029078/nativebase-generate-columns-in-row)
