### ISSUE TITLE
Grid not work as aspected if nested inside <Content>-Component

### ISSUE THREAD

**Issue by xstable** [GeekyAnts/react-native-easy-grid#57]
In the Docs (https://docs.nativebase.io/Components.html#Layout) I've found that <Grid> was inside <Content>.

But this does not work as descriped in the Docs, because it looks like this: 
![auswahl_491](https://user-images.githubusercontent.com/1778068/34535448-17ab0fbe-f0c2-11e7-8c8a-ca589ac82c85.jpg)

If I adjust the code like this to get rows:
```
import React, {Component} from "react";
import {
    Text,
} from 'react-native';
import {Container, Header, Left, Content} from 'native-base';
import {Col, Row, Grid} from 'react-native-easy-grid';

export default class Login extends Component<{}> {
    render() {
        return (
            <Container >
                <Header ><Left ><Text >Headline</Text ></Left ></Header >
                <Content >
                    <Grid >
                        <Row size={1} style={{backgroundColor: '#635DB7'}} ><Text >No.1</Text ></Row >
                        <Row size={3} style={{backgroundColor: '#00CE9F'}} ><Text >No.2</Text ></Row >
                    </Grid >
                </Content >
            </Container >
        );
    }
}
```

It Looks like this:
![auswahl_492](https://user-images.githubusercontent.com/1778068/34535437-0945ae48-f0c2-11e7-81a8-db3c59099814.jpg)

Only if I remove the `<Content>`-Tag, it seems to show in the right way:
![auswahl_493](https://user-images.githubusercontent.com/1778068/34535483-42d44778-f0c2-11e7-836c-08593772db39.jpg)

This seems to be an Bug!?, because the docs of nativebase.io suggest to have one `<Content>`-Tag at each Screen.

I've debugged it with react-devtools, and find out, that the first View inside the ScrollView has no flex-declaration.
If I add this like in the Screen, the two rows are shown in the right way: 

![auswahl_494](https://user-images.githubusercontent.com/1778068/34535712-12214c56-f0c3-11e7-98b8-343dc6afa357.jpg)

**Comment by akhil-geekyants** [comment]
@xstable NativeBase `<Content/>` component uses `<ScrollView>`. 

> If you're using `<Row/>` inside a `<ScrollView/>`, the height of the component would be flexible according to the content, though you can always apply the height styling. 

Link to the note [here](https://github.com/GeekyAnts/react-native-easy-grid#important-note-about-usage-with-scrollview-). 
Not a bug.

**Comment by xstable** [comment]
Ok, so what does this mean?
Does it mean I have to measure the Dimension-Height of the Screen, and set the height for the rows manually?
So in this way may it better not to use an <Content/>-Element ? (Seems to be easier in my opinion)
Or did it have downsides not to have an Content-Element nativebase.io?

**Comment by akhil-geekyants** [comment]
@xstable you can set the prop `contentContainerStyle={{flex:1}}` for `<Content/>` component to get the same behaviour as in docs.
```
<Content contentContainerStyle={{ flex: 1 }}>
  <Grid>
    <Col style={{ backgroundColor: '#635DB7' }}></Col>
    <Col style={{ backgroundColor: '#00CE9F' }}></Col>
  </Grid>
</Content>
```

**Comment by SupriyaKalghatgi** [comment]
@xstable Docs will be updated accordingly

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/native-base-docs/issues/75
