### ISSUE TITLE
Fixed width and fluid width combination

### ISSUE THREAD

**Issue by nolanrigo** [GeekyAnts/react-native-easy-grid#62]
Hello,

I'm developing a ReactNative application with NativeBase.io and I have a problem on fixed width and fluid width combination with the grid system.

There is my component tree

```
<Container>
  <Header />
  <Grid>
    <Col style={{ with: 140 }}/> (as Menu)
    <Col /> (as Content)
```

What I want :
|------|------------------------------------|

I would like my menu have pixel fixed size (like 140px) and my Content automatically adapt itself.

Actually, when I set the Menu width to pixel, all my Col goes to 50%/50% width.

What I have :
|---------------------|---------------------|

Do you have any suggestions ?

Nolan

**Comment by akhil-geekyants** [comment]
@nolanrigo you can set width like you did above. Attaching a gif

Code
```
import React, { Component } from 'react';
import { Container, Header, Content } from 'native-base';
import { Col, Row, Grid } from 'react-native-easy-grid';
export default class LayoutExample extends Component {
  render() {
    return (
      <Container>
        <Header />
        <Content>
          <Grid>
            <Col style={{ backgroundColor: '#635DB7', height: 200, width: 140 }}></Col>
            <Col style={{ backgroundColor: '#00CE9F', height: 200 }}></Col>
          </Grid>
        </Content>
      </Container>
    );
  }
}
```

Gif

![fixedwidth](https://user-images.githubusercontent.com/27768184/36596348-762ee4b2-18cb-11e8-8ed8-504d82df3540.gif)

**Comment by akhil-geekyants** [comment]
Closing this issue due to no response.
