### ISSUE TITLE
Android Only - Problem with nesting Grids in TouchableOpacity

### ISSUE THREAD

**Issue by MrMonotone** [GeekyAnts/react-native-easy-grid#66]
This does not work on Android. If you remove the TouchableOpacity it displays correctly.

```
<View>
    <Grid>
        <Row>
            <TouchableOpacity>
                <Gird>
                <Text>Test</Text>
                <Grid>
            </TouchableOpacity>
        </Row>
    </Grid>
</View>
```

This is the workaround I am using.
```
<View>
    <Grid>
        <TouchableOpacity>
            <Row>
                <Grid>
                <Text>Test</Text>
                <Grid>
            </Row>
        </TouchableOpacity>
    </Grid>
</View>
```

**Comment by akhil-geekyants** [comment]
@MrMonotone checked this. It is working fine for me. Attaching a gif.

![touchableopacity](https://user-images.githubusercontent.com/27768184/41154757-d625f152-6b38-11e8-896c-c4f1a9944010.gif)

Grid, Row and Col supports `onPress` event. You can use it like
```
<Grid onPress={() => console.warn("Hello")}>
    <Text>Test</Text>
</Grid>
        
```

**Comment by MrMonotone** [comment]
Fiddled with styling and got it working. There is still some weird styling issues that I experienced when I am using this. I just don't have the patience to track them down.
