### ISSUE TITLE
run-android stuck on starting: intent

### ISSUE THREAD

**Issue by Thomasin500** [GeekyAnts/react-native-easy-grid#69]
After installing and importing react-native-easy-grid 0.1.17 running:
`react-native run-android`
is now stuck at 
`Starting: Intent { cmp=com.awesomeproject/.MainActivity }`
![2018-06-27 22_48_08-window](https://user-images.githubusercontent.com/7727281/42013850-67e5f1fa-7a5c-11e8-81d3-78c8bb187c22.png)
![2018-06-27 22_49_34-window](https://user-images.githubusercontent.com/7727281/42013853-6968a46e-7a5c-11e8-9adc-bf0f5fe71936.png)

**Comment by akhil-geekyants** [comment]
@Thomasin500 Looks like this is an issue with `adb`.  See this StackOverflow [question](https://stackoverflow.com/questions/20564514/adb-is-not-recognized-as-an-internal-or-external-command-operable-program-or)

**Comment by Thomasin500** [comment]
That fixed the 'adb' problem so thank you, but I think I'm still missing some. Firing up the example from the readme does not show the grid as expected.
![2018-06-28 07_46_36-window](https://user-images.githubusercontent.com/7727281/42038190-92c460dc-7aa7-11e8-877b-7decd26576e0.png)
![2018-06-28 07_46_36-window](https://user-images.githubusercontent.com/7727281/42038195-938dcd0a-7aa7-11e8-8dd8-a6360bdac2e8.png)

**Comment by akhil-geekyants** [comment]
@Thomasin500 just give some background color for `<Col/>`.

Screenshot

![simulator screen shot - iphone 6 - 2018-06-28 at 19 32 17](https://user-images.githubusercontent.com/27768184/42039020-03d6aaac-7b0a-11e8-9c7b-abb506cb678c.png)


Sample code
```
import React, { Component } from 'react';
import { Col, Row, Grid } from 'react-native-easy-grid';
export default class App extends Component {
  render() {
    return (
      <Grid>
      <Col style={{backgroundColor:"red"}}></Col>
      <Col style={{backgroundColor:"blue"}}></Col>
  </Grid>
    );
  }
}
```

**Comment by Thomasin500** [comment]
got it! thanks!
