### ISSUE TITLE
Can't make the grid with 100% height, seems a bug

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/react-native-easy-grid#74]
https://github.com/GeekyAnts/NativeBase/issues/2142

**Comment by akhil-geekyants** [comment]
@SupriyaKalghatgi just need to wrap the content of SectionContainer with `<Row/>`

**Comment by akhil-geekyants** [comment]
@SupriyaKalghatgi https://github.com/GeekyAnts/NativeBase/issues/2142#issuecomment-405521510

**Comment by akhil-geekyants** [comment]
Sample code 
```
import React, { Component } from 'react';
import { Image, Dimensions, TouchableHighlight, ImageBackground, ScrollView } from "react-native";
import { Content, View, Icon, Text } from "native-base";
import { Col, Row, Grid } from 'react-native-easy-grid';

let categoriesCol1 = [{ title: "Lorem ipsum" }, { title: "Lorem ipsum" }, { title: "Lorem ipsum" }]
let categoriesCol2 = [{ title: "Lorem ipsum" }, { title: "Lorem ipsum" }, { title: "Lorem ipsum" }]
let win = Dimensions.get('window');

export default class App extends Component {
  render() {
    return (

      <ImageBackground style={styles.img} source={require("./cover.jpg")}>
        <Content style={{ height: win.height }}>
          <Grid style={{ height: win.height }}>
            <Row >
              <Col style={styles.col}>
                {categoriesCol1.map((item, idx) => {
                  return <SectionContainer key={idx} item={item} />;
                })}
              </Col>
              <Col style={styles.col}>
                {categoriesCol2.map((item, idx) => {
                  return <SectionContainer key={idx} item={item} />;
                })}
              </Col>
            </Row>
          </Grid>
        </Content>
      </ImageBackground>
    );
  }
}

const SectionContainer = ({ item, navigation }) => {
  return (
    <Row>
      <TouchableHighlight>
        <View style={{ justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: "#ffffff" }}>
          <Icon active name={"home"} style={styles.icon} />
          <Text style={styles.text}> {item.title} </Text>
        </View>
      </TouchableHighlight>
    </Row>

  );
};


const styles = {
  col: {
    flex: 0.5,
    backgroundColor: 'transparent'
  },
  img: {
    flex: 1,
    alignSelf: "stretch",
    width: win.width,
    height: win.height,
  },
  icon: {
    marginTop: 50,
    color: "#ffffff",
    fontWeight: '900',
    fontSize: 50
  },
  text: {
    fontSize: 28,
    color: '#ffffff',
    marginBottom: 50

  }
}
```

**Comment by ArtyomBaykov** [comment]
@akhil-geekyants in your screenshot I still see free space in the bottom. Is there a way to make those rows together full height without that free space?

**Comment by ArtyomBaykov** [comment]
![37323961_1957874787580869_3712900254165630976_n](https://user-images.githubusercontent.com/33861066/42862462-9ed4f76e-8a70-11e8-92e8-d760e4bec755.png)

@akhil-geekyants  I checked it even tried to add marginBottom:0 to that row which you said to include while now all rows have margins on the bottoms even the last one which makes free space on the bottom again with scrolling.  So how all those margins can be removed?  marginBottom is not working.

**Comment by akhil-geekyants** [comment]
@ArtyomBaykov can you check the code in this issue comment https://github.com/GeekyAnts/NativeBase/issues/2142#issuecomment-405597838

**Comment by ArtyomBaykov** [comment]
@akhil-geekyants I checked it. contentContainerStyle shows only image without rows and cols. I placed style instead of contentContainerStyle margins are removed, the scroll is removed but there is still free space (marginBottom) on the bottom of the screen under the last row.

**Comment by SupriyaKalghatgi** [comment]
https://github.com/GeekyAnts/NativeBase/issues/2142#issuecomment-405597838
this looks appropriate to what is needed

**Comment by SupriyaKalghatgi** [comment]
Closing issue due to no response
