### ISSUE TITLE
style doesn't apply when use with styled-components 

### ISSUE THREAD

**Issue by jamalx31** [GeekyAnts/react-native-easy-grid#79]
```
import { Row } from 'react-native-easy-grid'

const StyledRow = styled(Row)`
   background-color: red; (Works!)
`

const StyledRow2 = styled(StyledRow)`
   background-color: yellow; (Doesn't work)
`
```
overriding the Row style doesn't work. and it works with other Component like View.

**Comment by jamalx31** [comment]
Found the issue.
```<Row style={[{backgroundColor: 'red'},[{ backgroundColor: 'yellow' }]]}>```
the background color will be `red` even tho the style is valid and
```<View style={[{backgroundColor: 'red'},[{ backgroundColor: 'yellow' }]]}>```
will render `yellow` bg

**Comment by SupriyaKalghatgi** [comment]
@jamalx31 Do you need any help here?
