### ISSUE TITLE
The Grid row layout does not show content properly

### ISSUE THREAD

**Issue by thechamp** [GeekyAnts/react-native-easy-grid#8]
Neither the screen was divided in 4:1 horizontally nor the content is shown properly. See the screenshot of code and result on android simulator attached.

<img width="1055" alt="screen shot 2016-08-21 at 8 04 57 pm" src="https://cloud.githubusercontent.com/assets/2319535/17837814/d918a3d6-67da-11e6-9ffb-39f770a02f89.png">

**Comment by sankhadeeproy007** [comment]
`<Content />` being a ScrollView component, the Grid inside it only takes as much height as the content inside. Replace `<Content />` with `<View />` and that should work. And if you want to use `<Content />` please specify height for the components inside.

**Comment by thechamp** [comment]
<img width="986" alt="screen shot 2016-08-27 at 10 34 51 am" src="https://cloud.githubusercontent.com/assets/2319535/18025272/65c9f1fc-6c42-11e6-9103-e9a0aef764c9.png">

**Comment by sankhadeeproy007** [comment]
Use flex:1 with View

**Comment by thechamp** [comment]
That works, thanks.

**Comment by Anima-t3d** [comment]
The picker does not show in `Row` on android (1a does not show the picker on android), I fixed it by wrapping the `Picker` in a `Col` inside the `Row` (see 2a). Related to [https://github.com/facebook/react-native/issues/6110#issuecomment-286355942](https://github.com/facebook/react-native/issues/6110#issuecomment-286355942):
```jsx
<Grid>
    <Row>
        <Text>1a</Text>
        <Picker iosHeader="Select one" mode="dropdown" selectedValue={this.state.personal.gender} onValueChange={(value)=> this._updatePersonalState({gender: value})}> {this._getGenderOptions().map((option) =>
            <Picker.Item key={option.key} label={option.label} value={option.key} /> )}
        </Picker>
    </Row>
    <Row>
        <Text>2a</Text>
        <Col>
        <Picker iosHeader="Select one" mode="dropdown" selectedValue={this.state.personal.gender} onValueChange={(value)=> this._updatePersonalState({gender: value})}> {this._getGenderOptions().map((option) =>
            <Picker.Item key={option.key} label={option.label} value={option.key} /> )}
        </Picker>
        </Col>
    </Row>
</Grid>
```

**Comment by cyclops24** [comment]
@Anima-t3d I have a same issue.
NativeBase picker not visible in Col or Row.

**Comment by cyclops24** [comment]
@Anima-t3d based on https://github.com/GeekyAnts/NativeBase/issues/457 I add `{flex:1}` to Picker component and now it's show well.
I don't know why this happens. Do you have any idea guys?

**Comment by aboeglin** [comment]
> <Content /> being a ScrollView component, the Grid inside it only takes as much height as the content inside. Replace <Content /> with <View /> and that should work. And if you want to use <Content /> please specify height for the components inside.

@sankhadeeproy007 

Also, Content is supposed to be the Body of the UI. Easy-grid is supposed to work well with NativeBase and remove the need to use View. I think it would make more sense to provide an option to render a Content without a ScrollView, rather than forcing to use View with a flex:1 to take a full screen height. It seems weird to try to replace the flex system, by using it in one of the most common cases. I know it would be a NativeBase issue, as the Content class is actually defined there. 

Let me know what are your thoughts on that !
