### ISSUE TITLE
Height style ignored if passed using StyleSheet

### ISSUE THREAD

**Issue by eric-burel** [GeekyAnts/react-native-easy-grid#80]
Hi,

When I define a Row height using StyleSheet, it is not taken into account in the current implementation. This line handle the `flex` property: [https://github.com/GeekyAnts/react-native-easy-grid/blob/master/Components/Row.js#L14](https://github.com/GeekyAnts/react-native-easy-grid/blob/master/Components/Row.js#L14).
My guess is that checking `props.style.height` is not sufficient. However I am very new to React Native so I could not say how `StyleSheet` interact with the `style` prop.

Passing the height directly in the `style` props does work however.

Working example:
```js
<Row style={{ height: "auto" }}>
    ...
 </Row>
```
Not working example:
```js
const styles = StyleSheet.create({ row: { height: "auto" } })
...
<Row style={styles.row}>
  ...
</Row>
```

**Comment by shubhang93** [comment]
Yes, I am facing the same issue with styled components as well. Other properties seem to work fine

**Comment by SupriyaKalghatgi** [comment]
React Native does not support `height: 'auto'`

**Comment by SupriyaKalghatgi** [comment]
Working fine

![image](https://user-images.githubusercontent.com/13464885/54191153-579dd980-44db-11e9-960b-a29d6fe7e9ba.png)

**Comment by aneeskodappana** [comment]
is it possible to fit the height based on the content instead of static height?
