### ISSUE TITLE
row height

### ISSUE THREAD

**Issue by sebinator** [GeekyAnts/react-native-easy-grid#82]
is it possible to fit the height based on the content instead of static height?

**Comment by ShetlandJ** [comment]
Is this repo dead?

**Comment by SupriyaKalghatgi** [comment]
@sebinator @ShetlandJ There is no static height mentioned here

![image](https://user-images.githubusercontent.com/13464885/54189627-31c30580-44d8-11e9-9ae8-823a36650780.png)

**Comment by bneigher** [comment]
@SupriyaKalghatgi 
not clear if your response is an answer or what... do you mind explaining at least if this is not possible?  That way (if not) someone would be inclined to make a PR

**Comment by waqaramjad** [comment]
facing same issue

**Comment by canercak** [comment]
same issue
