### ISSUE TITLE
Columns do not wrap

### ISSUE THREAD

**Issue by Ahagan** [GeekyAnts/react-native-easy-grid#84]
When I have specified that a width for a grid and row but the total size of the columns exceeds that of the row, the columns do not wrap to the next line.

E.g.
I have 4 columns of size 4 (total 16), I would expect the last column to wrap onto the next line. At the moment, the Grid resizes to fit all into one row.
```
<Grid size={12}>
   <Row size={12}>
      <Col size={4}>
           ....
     </Col>
     <Col size={4}>
           ....
     </Col>
     <Col size={4}>
           ....
     </Col>
     <Col size={4}>
           ....
     </Col>
   </Row>
</Grid>
```

**Comment by SupriyaKalghatgi** [comment]
@Ahagan I am not at all clear with your issue. Please create new issue and follow the issue template while doing so

**Comment by matikups** [comment]
Actually, the issue is pretty clear.
Please don't close issues if they don't lead to a solution.

I'm having this question too.
Any ideas?
