### ISSUE TITLE
can't use for odd number of elemens

### ISSUE THREAD

**Issue by akashkrshukla** [GeekyAnts/react-native-easy-grid#88]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/react-native-easy-grid/issues
- []   Use the latest React Native Easy Grid release
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

**Comment by pghtimwilson** [comment]
Did you literally create a dup with #89 as well?

**Comment by akashkrshukla** [comment]
Used Scrollview in horizontal={true } mode and objective solved.
