### ISSUE TITLE
can't use for odd number of elements

### ISSUE THREAD

**Issue by akashkrshukla** [GeekyAnts/react-native-easy-grid#89]
## I have gone through these following points
- []   Check latest documentation: https://docs.nativebase.io/
- []   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/react-native-easy-grid/issues
- []   Use the latest React Native Easy Grid release
- []   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- []   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- []   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

**Comment by akashkrshukla** [comment]
whenever i try to align odd number of items like 5 in first column and 6 in second column , it produces totally unexpected results. The problem is this way i can't use it for automating processes.

**Comment by pghtimwilson** [comment]
You might have better success if you provide an example. Provide some sample data, screenshot etc... It is possible this might just be working by design.

**Comment by akashkrshukla** [comment]
Used in combination with ScrollView and it worked as expected
