### ISSUE TITLE
Row layout fixed height + fluid height not working

### ISSUE THREAD

**Issue by danieljvdm** [GeekyAnts/react-native-easy-grid#9]
```
<Grid>
  <Row style={{ height: 20 }}></Row>
  <Row style={{ backgroundColor: 'red' }}></Row>
</Grid>
```

This code doesn't create the desired result of having a fixed height row with a fluid height one. Instead it ignores the height and layouts the rows out with equal heights. If I replace `Row` with `Col` and `height` with `width` it works.

**Comment by johnygomez** [comment]
maybe try specifying the size
```
<Grid>
  <Row style={{ height: 20 }} size={0}></Row>
  <Row style={{ backgroundColor: 'red' }} size={100}></Row>
</Grid>
```
but don't think it's wise solution..

**Comment by ianfisk** [comment]
If they merge the PR above, adding `height` to the row style will set `flex: 0` and thus the height specified will be used (right now `flex` is set to 1 making the height be ignored). Until then, if you also specify a `flex` of 0 with your desired height, it should work. I.e. `<Row style={{ flex: 0, height: 20 }}></Row>`
