### ISSUE TITLE
Lodash Vulnerability 

### ISSUE THREAD

**Issue by crcommons** [GeekyAnts/react-native-easy-grid#91]
## I have gone through these following points
- [x]   Check latest documentation: https://docs.nativebase.io/
- [x]   Check for existing open/closed issues for a possible duplicate before creating a new issue: https://github.com/GeekyAnts/react-native-easy-grid/issues
- [x]   Use the latest React Native Easy Grid release
- [x]   Check examples from NativeBase KitchenSink https://github.com/GeekyAnts/NativeBase-KitchenSink
- [x]   For discussion purpose make use of NativeBase Slack: http://slack.nativebase.io/
- [x]   For queries related to theme, check [Theme Variables](https://docs.nativebase.io/docs/ThemeVariables.html) from Docs and live NativeBase Theme Editor http://nativebase.io/customizer/

## Issue Description
Lodash Prototype Pollution: https://npmjs.com/advisories/1065

I'm wondering if there is a patch to upgrade the lodash dependency or when it is expected?

### node, npm, package.json, xcode version
npm -v 6.7.0
### Expected behaviour
When I install react-native-easy-grid, it should not return a High security vulnerability.
### Actual behaviour
When I install, it returns: 

High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.12                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-native-easy-grid                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ react-native-easy-grid > lodash                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1065

**Comment by maamounapprise** [comment]
When are we seeing a release? @BlueT

**Comment by BlueT** [comment]
@maamounapprise My PR has been reviewed and merged (by @sanketsahusoft @sankhadeeproy007 @PlabanJr) in https://github.com/GeekyAnts/react-native-easy-grid/pull/93

Now waiting maintainer(s) to publish new release to npmjs

**Comment by PlabanJr** [comment]
Published 👍
